Add 1.20 Release Notes shadows to groups
kubernetes/k8s.io pull request #1277
Opened 2020-09-23 17:09 UTC by JamesLaverack

This adds all four release notes shadows on the 1.20 Kubernetes release team to both the release team mailing list and the release team shadows mailing list.

This is part of the release team shadow onboarding process.

2020-09-23 20:39 UTC, spiffxp commented
Needs rebase

2020-09-24 11:31 UTC, savitharaghunathan requested changes
Hi, @JamesLaverack 👋. Can you sort the email id's in alphabetical order, please?

2020-09-28 11:44 UTC, JamesLaverack commented
@spiffxp Rebased.
@savitharaghunathan Alphabetised.

I've force-pushed the new commit.

2020-09-29 21:06 UTC, dims commented
/approve
/lgtm

2020-09-29 21:07 UTC, merged