Update Google Group memberships for Cluster API and Cluster API Provider AWS
kubernetes/k8s.io pull request #1297
Opened 2020-10-02 17:54 UTC by randomvariable

To match current maintainers

2020-10-02 17:56 UTC, detiber commented
/lgtm

2020-10-05 15:24 UTC, detiber commented
/lgtm

2020-10-05 17:44 UTC, nader-ziada commented
/lgtm

2020-10-07 18:01 UTC, justaugustus requested changes
Two comments :)

2020-10-09 23:06 UTC, randomvariable commented on groups/groups.yaml
> +      - arudoi@newrelic.com
@rudoi , dm me your address and i'll update.

2020-10-13 15:10 UTC, randomvariable commented on groups/groups.yaml
> +      - arudoi@newrelic.com
Updated.

2020-10-13 15:11 UTC, randomvariable commented on groups/groups.yaml
>        - nicklaneovi@gmail.com
Done

2020-10-13 16:09 UTC, nader-ziada commented
/lgtm

2020-10-14 02:02 UTC, justaugustus commented
/lgtm
/assign @dims

2020-10-14 12:24 UTC, dims commented
/approve
/lgtm

2020-10-14 12:27 UTC, merged