Add jeremyrickard as sig-release technical lead
kubernetes/k8s.io pull request #1529
Opened 2021-01-14 01:22 UTC by hasheddan

Adds @jeremyrickard to appropriate groups and OWNERS as part of sig technical lead onboarding.

(Note: Jeremy was already in the general `leads` group so he is not added in this PR)

xref: https://github.com/kubernetes/sig-release/issues/1421

/hold
/assign @justaugustus @saschagrunert

2021-01-14 01:33 UTC, dims commented
/approve

2021-01-14 01:58 UTC, justaugustus requested changes
@hasheddan -- A few nits + let's add @jeremyrickard as an owner for release-team@kubernetes.io as well.

There are a few of us in @kubernetes/sig-release-leads that hold multiple roles...
Yourself, @saschagrunert, and I are:
- SIG leadership
- Release Managers
- RelEng subproject owners

We need to codify this somewhere, but I've been roughly going by these rules:
- All SIG Release leadership should have (owner-level) access to moderate _contact-only_ Google Groups (roughly everything that isn't prepended with `k8s-`)
- Only Release Managers and RelEng subproject owners should be on groups that grant IAM to GCP
- Only RelEng subproject owners should be on `k8s-infra-release-admins`

/hold
/retitle groups: Add Jeremy Rickard as a SIG Release Technical Lead

2021-01-14 01:58 UTC, justaugustus commented on OWNERS_ALIASES
> +    - jeremyrickard # subproject owner / Release Manager / SIG Technical Lead
```suggestion
    - jeremyrickard # SIG Technical Lead
```

2021-01-14 01:58 UTC, justaugustus commented on OWNERS_ALIASES
> +    - jeremyrickard # subproject owner / Release Manager / SIG Technical Lead
```suggestion
    - jeremyrickard # SIG Technical Lead
```

2021-01-14 01:58 UTC, justaugustus commented on groups/sig-release/groups.yaml
> +      - jeremy.r.rickard@gmail.com
Drop.

2021-01-14 01:58 UTC, justaugustus commented on groups/sig-release/groups.yaml
> +      - jeremy.r.rickard@gmail.com
Drop.

2021-01-15 00:25 UTC, hasheddan commented
@justaugustus updates made :+1:

2021-01-15 00:28 UTC, justaugustus commented
Awesome, thanks @hasheddan!
/lgtm
/approve
/hold cancel

2021-01-15 00:29 UTC, merged