Add infra/gcp/ensure-audit-perms.sh
kubernetes/k8s.io pull request #1648
Opened 2021-02-16 00:20 UTC by hh

/assign @spiffxp

2021-02-16 14:41 UTC, spiffxp requested changes
This needs changes to run as-is

2021-02-16 14:41 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +}
this looks like leftover copy-pasta from ensure-staging-storage.sh, please remove or update instructions to be relevant to this script

2021-02-16 14:41 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +           --role=$ROLE
```suggestion
    gcloud organizations add-iam-policy-binding \
           --member="${GROUP} \
           --role="${ROLE}"
           "${ORG}"
```

2021-02-16 14:41 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +GROUP=group:k8s-infra-gcp-auditor@kubernetes.io
```suggestion
ORG="${GCP_ORG}
GROUP="group:k8s-infra-gcp-auditor@kubernetes.io"
```

2021-02-16 14:41 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +#!/usr/bin/env bash
This file needs to be `chmod +x`

2021-02-16 14:41 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +roles/serviceusage.serviceUsageConsumer"
For followup, we should either:
- collapse these into a custom role (I'll try to writeup what I did for prow's role, maybe it's time to script composition of predefined roles into a custom role)
- consider granting `roles/viewer` to simplify/avoid brittleness (though this does go against the principle of using most specific permissions possible in production)

2021-02-16 14:44 UTC, spiffxp commented
In the meantime, to hopefully unblock, I have manually run:
```
gcloud organizations add-iam-policy-binding \
  --member=group:k8s-infra-gcp-auditors@kubernetes.io \
  --role=roles/secretmanager.viewer \
  758905017065
```

2021-02-16 18:34 UTC, spiffxp commented on infra/gcp/ensure-audit-perms.sh
> +roles/serviceusage.serviceUsageConsumer"
Opened https://github.com/kubernetes/k8s.io/issues/1656 to describe creation of custom role

2021-02-17 22:51 UTC, hh commented
Putting on hold for a bit while I focus on getting the audit PR creating prow job working.
/hold

2021-02-18 23:27 UTC, spiffxp commented
/close
Closing in favor of https://github.com/kubernetes/k8s.io/pull/1679

2021-02-18 23:27 UTC, closed without merging