[WIP] Add tests for data validation
kubernetes/k8s.io pull request #1759
Opened 2021-03-04 22:40 UTC by ameukam

Add policices written in [rego](https://www.openpolicyagent.org/docs/latest/policy-language/) that validate kubernetes resouces. Only the ingresses are covered.
THis is heavily inspired from https://github.com/deliveryhero/helm-charts/tree/master/ci/helm-conftest-policies.
[conftest](https://github.com/open-policy-agent/conftest) will be used against those policies.

Ref: https://github.com/kubernetes/k8s.io/issues/1734

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2021-03-04 22:41 UTC, ameukam commented
/assign @spiffxp

2021-03-04 23:01 UTC, ameukam commented
testing policies: 

```shell
time conftest test -p policies/ */*.yaml
WARN - k8s.io/ingress-canary.yaml - main - Ingress/k8s-io: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-prod-v6.yaml - main - Ingress/k8s-io-v6: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - node-perf-dash.k8s.io/ingress.yaml - main - Ingress/node-perf-dash: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - gcsweb.k8s.io/ingress.yaml - main - Ingress/gcsweb: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-canary-v6.yaml - main - Ingress/k8s-io-v6: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-prod.yaml - main - Ingress/k8s-io: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - perf-dash.k8s.io/ingress.yaml - main - Ingress/perfdash: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.

249 tests, 242 passed, 7 warnings, 0 failures, 0 exceptions
conftest test -p policies/ */*.yaml  0.30s user 0.02s system 165% cpu 0.192 total
```

2021-03-04 23:03 UTC, ameukam commented
We are not doing static analysis of kubernetes resources so we may need something like [kube-linter](https://github.com/stackrox/kube-linter) or [kubeval](https://kubeval.instrumenta.dev/).

2021-03-08 22:08 UTC, ameukam commented
I added more deprecation policies. 

```shell
time conftest test -p policies/ */*.yaml
WARN - k8s.io/ingress-canary-v6.yaml - main - Ingress/k8s-io-v6: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-prod.yaml - main - Ingress/k8s-io: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - perf-dash.k8s.io/ingress.yaml - main - Ingress/perfdash: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-prod-v6.yaml - main - Ingress/k8s-io-v6: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - node-perf-dash.k8s.io/ingress.yaml - main - Ingress/node-perf-dash: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - artifactserver/manifest.yaml - main - Deployment/artifactserver: API extensions/v1beta1 for Deployment has been deprecated, use apps/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-cainjector: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-cainjector: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - Role/cert-manager-cainjector:leaderelection: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - RoleBinding/cert-manager-cainjector:leaderelection: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-webhook:auth-delegator: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - RoleBinding/cert-manager-webhook:webhook-authentication-reader: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - Role/cert-manager:leaderelection: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - RoleBinding/cert-manager:leaderelection: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-issuers: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-clusterissuers: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-certificates: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-orders: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-challenges: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRole/cert-manager-controller-ingress-shim: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-issuers: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-clusterissuers: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-certificates: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-orders: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-challenges: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - cert-manager/cert-manager.yaml - main - ClusterRoleBinding/cert-manager-controller-ingress-shim: API rbac.authorization.k8s.io/v1beta1 is deprecated from Kubernetes 1.20, use rbac.authorization.k8s.io/v1 instead.
WARN - gcsweb.k8s.io/ingress.yaml - main - Ingress/gcsweb: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.
WARN - k8s.io/ingress-canary.yaml - main - Ingress/k8s-io: API extensions/v1beta1 for Ingress is deprecated from Kubernetes 1.14, use networking.k8s.io/v1beta1 instead.

83 tests, 55 passed, 28 warnings, 0 failures, 0 exceptions
conftest test -p policies/ */*.yaml  0.28s user 0.03s system 168% cpu 0.185 total
```

2021-03-23 19:58 UTC, spiffxp requested changes
Thank you for doing this!

This is close to merge-and-iterate for me. Can you add a README explaining what these are / how to use them?

Long term I think we should consider how to organize these, possibly using gatekeeper's library layout as a template

2021-03-26 23:59 UTC, ameukam commented
@spiffxp Added a README.

2021-03-27 00:31 UTC, spiffxp approved these changes
/approve
/lgtm

2021-03-27 00:34 UTC, merged