gcp/lib: set builder permission instead of editor
kubernetes/k8s.io pull request #1773
Opened 2021-03-10 10:44 UTC by cpanato

The role `roles/cloudbuild.builds.editor` looks like does not have all the necessary permissions to push images from gcb (https://cloud.google.com/build/docs/iam-roles-permissions)

the builder role (`roles/cloudbuild.builds.builder`) have the permission (`storage.buckets.get`) to make it able to push the images.

I'm not sure if this is the correct way to deal or we add another role just to add the `storage.buckets.get` permission.

/assign @spiffxp 

Fixes: https://github.com/kubernetes/k8s.io/issues/1772

2021-03-10 22:43 UTC, spiffxp reviewed
I'm honestly not sure myself, seems ok but I will give this a shot tomorrow. Want to make sure we don't break other staging builds. 

If you move this to just the special case for your staging repo I will approve and deploy today.

2021-03-10 23:11 UTC, spiffxp requested changes
Changed my mind, responded in linked issue

2021-03-10 23:21 UTC, justaugustus commented on infra/gcp/lib.sh
> +        --role roles/cloudbuild.builds.builder
Right, the GCB SA needs access to write to GCR, not the operator.
The operator only needs access to execute the GCB job.

2021-03-11 07:51 UTC, cpanato commented on infra/gcp/lib.sh
> +        --role roles/cloudbuild.builds.builder
got it will close this and see other alternatives

/close

2021-03-11 07:51 UTC, closed without merging