Adding dims as approver for k8s.io
kubernetes/k8s.io pull request #1799
Opened 2021-03-17 01:38 UTC by dims

@thockin unblocked me from being able to do things with https://github.com/kubernetes/k8s.io/pull/1796

thanks Tim! 

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

2021-03-17 01:38 UTC, dims commented
/assign @thockin @spiffxp @ixdy

2021-03-17 04:10 UTC, spiffxp approved these changes
/approve
/lgtm

2021-03-17 04:18 UTC, spiffxp requested changes
since I don't have approve, let's make this followup I never got around to today mentioned in https://github.com/kubernetes/k8s.io/pull/1792#discussion_r595494784

I'm also fine if we decide to prune this list of people but I feel like parity first, prune followup

2021-03-17 04:18 UTC, spiffxp commented on k8s.io/OWNERS
> +- dims
We should get parity between approvers and this group https://github.com/kubernetes/k8s.io/blob/390481ba911059c23a2739cb56bccf8be3ea183b/groups/groups.yaml#L543-L554

```suggestion
- aojea
- bentheelder
- cblecker
- dims
- spiffxp
```

(you'll also need to remove ixdy)

Can you update this to add yourself to the group? Add thockin and myself (@google.com) if it's not too much trouble?

2021-03-17 04:38 UTC, thockin commented
/approve

On Tue, Mar 16, 2021, 9:19 PM Kubernetes Prow Robot <
***@***.***> wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by: *dims
> <https://github.com/kubernetes/k8s.io/pull/1799#>*
> To complete the pull request process
> <https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process>,
> please ask for approval from *ixdy* after the PR has been reviewed.
>
> The full list of commands accepted by this bot can be found here
> <https://go.k8s.io/bot-commands?repo=kubernetes%2Fk8s.io>.
> Needs approval from an approver in each of these files:
>
>    - *k8s.io/OWNERS
>    <https://github.com/kubernetes/k8s.io/blob/main/k8s.io/OWNERS>*
>
> Approvers can indicate their approval by writing /approve in a comment
> Approvers can cancel approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/k8s.io/pull/1799#issuecomment-800781578>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKWAVCXLURLLDGALCJT2DDTEAUUVANCNFSM4ZJUU4CQ>
> .
>

2021-03-22 20:24 UTC, dims commented
/retest

2021-03-22 20:24 UTC, dims commented
@spiffxp this is ready now. thanks!

2021-03-22 20:42 UTC, spiffxp approved these changes
/lgtm

Group updates are missing but that can be a followup

2021-03-22 20:43 UTC, merged