Add github admins for k8s-staging-ci-robot
kubernetes/k8s.io pull request #1861
Opened 2021-03-31 21:45 UTC by ameukam

For https://github.com/kubernetes/k8s.io/issues/1394, we will need
a new github account acting as a new bot
[k8s-staging-ci-robot](https://github.com/k8s-staging-ci-robot). Adding
a new mailing list that list be use for administration of this robot.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2021-03-31 21:46 UTC, ameukam commented
/assign @spiffxp

2021-03-31 23:58 UTC, spiffxp requested changes
Idea is fine. Naming nit to address

2021-03-31 23:58 UTC, spiffxp commented on groups/groups.yaml
> +    name: github-k8s-ci-staging-robot
Can we rename to k8s-infra-ci-robot?

2021-04-01 17:29 UTC, ameukam commented on groups/groups.yaml
> +    name: github-k8s-ci-staging-robot
@spiffxp Fixed.

2021-04-01 19:41 UTC, spiffxp approved these changes
/approve
/lgtm

2021-04-01 19:45 UTC, merged