Initial version of repo tag dumper
kubernetes/k8s.io pull request #2043
Opened 2021-05-13 16:48 UTC by justinsb

Dumps tags to json for later grepping / import.

Issue #2037

2021-05-19 17:38 UTC, spiffxp requested changes
It looks like there's still a bunch of iteration happening in https://github.com/kubernetes/k8s.io/issues/2037 so I'm not even sure if this intended to land yet, or at all.

I took a pass with a "merge-and-iterate" perspective, these are the things that block.

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/main.go
> +package main
Needs boilerplate

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/go.mod
> +go 1.14
```suggestion
go 1.16
```

Unless there's a reason to use 1.14?

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/main.go
> +			*/
Not a fan of checking in commented-out code.  Why was this commented out?  Dropping a TODO would be more helpful
```suggestion
```

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/main.go
> +	*/
Same thing re: commented-out code
```suggestion
```

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/main.go
> +// Based on gcrane list command  https://github.com/google/go-containerregistry/blob/master/cmd/gcrane/cmd/list.go
Need more a description on what this is doing and why

2021-05-19 17:38 UTC, spiffxp commented on metrics/access-logs/sniped/go.mod
> +module sniped
I don't think this should be in `metrics/access-logs`

It doesn't do anything with metrics (read or publish), and it definitely doesn't do anything with access logs

I guess we lack a "useful miscellaneous tooling" directory.  I would either use `audit/` as the home for tools that help audit our project, or make a new `tools/` directory.  Then put `sniped` under that

2021-09-03 10:12 UTC, spiffxp commented
Is this used or intended for merge? I'm going to close next week if not.

ref: https://github.com/kubernetes/k8s.io/issues/1834

2021-09-03 10:13 UTC, spiffxp commented
/cc @BobyMCbobs @Riaankl @hh

2021-09-07 02:31 UTC, BobyMCbobs commented
> /cc @BobyMCbobs @Riaankl @hh

This might be interesting to refer to again later on. I believe that we're parsing the paths visited from the pii logs to get the image repo and tag

2021-09-08 14:40 UTC, spiffxp commented
/close

2021-09-08 14:41 UTC, closed without merging