image-builder/capg: add more permissions to the service account
kubernetes/k8s.io pull request #2061
Opened 2021-05-19 09:42 UTC by cpanato

after we merge: https://github.com/kubernetes/k8s.io/pull/2057 and https://github.com/kubernetes/k8s.io/pull/2025

the periodic job ran https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-image-builder-gcp-all-nightly/1394944554532081664 but we got an error

```
Error creating instance: googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/k8s-staging-cluster-api-gcp/zones/us-central1-a', forbidden
```

So looks like we need to give a bit more permissions to the svcacc in order to work. 
doing a search saw the `role/editor` have the necessary permissions. However, I don't know if this the correct way to enable it.

/assign @spiffxp @ameukam

2021-05-19 09:51 UTC, cpanato commented on infra/gcp/ensure-staging-storage.sh
> +    ensure_project_role_binding "${STAGING_PROJECT}" "serviceAccount:${serviceaccount}" "roles/compute.instanceAdmin.v1"
maybe this is not needed not sure

2021-05-19 09:52 UTC, cpanato commented on infra/gcp/ensure-staging-storage.sh
> +    ensure_project_role_binding "${STAGING_PROJECT}" "serviceAccount:${serviceaccount}" "roles/compute.instanceAdmin.v1"
Arnaud post this doc: https://www.packer.io/docs/builders/googlecompute

2021-05-19 10:19 UTC, ameukam commented on infra/gcp/ensure-staging-storage.sh
> +    ensure_project_role_binding "${STAGING_PROJECT}" "serviceAccount:${serviceaccount}" "roles/editor"
This is not needed for packer images builds. This role allow permissions on services outside of the scope of `compute.googleapis.com` service.

2021-05-19 17:14 UTC, spiffxp requested changes

2021-05-19 17:14 UTC, spiffxp commented on infra/gcp/ensure-staging-storage.sh
> +    ensure_project_role_binding "${STAGING_PROJECT}" "serviceAccount:${serviceaccount}" "roles/iam.serviceAccountUser"
The reason I'm wary of this binding is that it's at the project level, meaning you're letting this service account act as _any_ service account in the project.

Typically I would expect this binding to be set directly the service account that is intended to be used, which you would do in our bash via:
```bash
ensure_serviceaccount_role_binding "foo@bar.iam.gserviceaccount.com" "user:bob@example.com" "roles/iam.serviceAccountUser"
```

2021-05-21 08:17 UTC, cpanato commented on infra/gcp/ensure-staging-storage.sh
> +    ensure_project_role_binding "${STAGING_PROJECT}" "serviceAccount:${serviceaccount}" "roles/iam.serviceAccountUser"
removed the items

2021-06-02 11:21 UTC, ameukam commented
/lgtm
/approve

Let's try with this set of permissions.

2021-06-02 11:26 UTC, merged

2021-06-02 11:36 UTC, ameukam commented
Running : `./infra/gcp/ensure-staging-storage.sh`

2021-06-02 11:40 UTC, cpanato commented
@ameukam let me know when is ready and I will try to trigger the job

2021-06-02 19:41 UTC, ameukam commented
Vaccine shot forced me to stay away from computers today. I got: 
```shell
Ensuring GKE clusters in 'k8s-infra-prow-build-trusted' can run pods in 'test-pods' as 'gcb-builder-cluster-api-gcp@k8s-staging-cluster-api-gcp.iam.gserviceaccount.com' 
./lib_iam.sh: line 228: local: serviceaccount: readonly variable
```

I'm looking into it.