infra/gcp/prow: Add e2e project for sig-scalability
kubernetes/k8s.io pull request #2195
Opened 2021-06-10 23:03 UTC by ameukam

Add e2e projects for sig-scalability prowjobs that need 5K nodes.
Initial suggestion : https://github.com/kubernetes/test-infra/pull/22430#pullrequestreview-677953930

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2021-06-10 23:03 UTC, ameukam commented
/assign @spiffxp

2021-06-11 23:50 UTC, spiffxp requested changes
I think I left my comment at pending so in case it doesn't come through: I would rather start with just the one project instead of provisioning five projects. That's five times more capacity than we have provisioned today. I'm in no rush to spend even more than we do today without concrete justification

2021-06-14 18:58 UTC, ameukam commented on infra/gcp/prow/ensure-e2e-projects.sh
> +
@spiffxp Somehow I missed your comment. 😞
PR updated.

2021-06-15 20:20 UTC, spiffxp requested changes
One nit otherwise lgtm

2021-06-15 20:20 UTC, spiffxp commented on infra/gcp/infra.yaml
> +      # e2e projects for scalability jobs with 5000 nodes(--gcp-project-type=scalability-project)
```suggestion
      # e2e projects for scalability jobs with 5000 nodes
```

2021-06-15 20:39 UTC, ameukam commented on infra/gcp/infra.yaml
> +      # e2e projects for scalability jobs with 5000 nodes(--gcp-project-type=scalability-project)
Fixed.

2021-06-15 20:40 UTC, spiffxp approved these changes
/approve
/lgtm

2021-06-15 20:40 UTC, spiffxp commented
I'll take care of deploying

2021-06-15 20:41 UTC, merged

2021-06-15 20:52 UTC, spiffxp commented
Deployed
```
$ ./ensure-e2e-projects.sh k8s-infra-e2e-scale-5k-project
Ensuring external secrets exist for use by k8s-infra-prow-build-trusted
  Ensuring secret 'cncf-ci-github-token' exists in 'k8s-infra-prow-build-trusted' and is owned by 'k8s-infra-ii-coop@kubernetes.io'
  Updated secret [cncf-ci-github-token].
  Ensuring secret 'snyk-token' exists in 'k8s-infra-prow-build-trusted' and is owned by 'k8s-infra-code-organization@kubernetes.io'
  Updated secret [snyk-token].
Ensuring e2e projects used by prow...
  Configuring e2e project: k8s-infra-e2e-scale-5k-project
    Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-infra-e2e-scale-5k-project].
    Waiting for [operations/cp.6812659568010387061] to finish...
    ..done.
    billingAccountName: billingAccounts/018801-93540E-22A20E
    billingEnabled: true
    name: projects/k8s-infra-e2e-scale-5k-project/billingInfo
    projectId: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -1,2 +1 @@
    -- member: user:spiffxp@google.com
    -  role: roles/owner
    +[]
    Ensure stale role bindings have been removed from e2e project: k8s-infra-e2e-scale-5k-project
      no stale bindings slated for removal
    Ensuring only APIs necessary for kubernetes e2e jobs to use e2e project: k8s-infra-e2e-scale-5k-project
    plan to enable/disable the following services
    to_enable:
      - compute.googleapis.com
      - containerregistry.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com
      - storage-component.googleapis.com
    to_disable: []
    Operation "operations/acf.p2-783965148085-e3561dac-7684-4ec5-8a4e-087848353038" finished successfully.
    Operation "operations/acf.p2-783965148085-73b68eda-a5fc-45e5-a827-90df93bfa3ef" finished successfully.
    Operation "operations/acf.p2-783965148085-69a4fc7c-d39b-44da-9978-eb05e6bd4abc" finished successfully.
    Operation "operations/acf.p2-783965148085-17922383-9f5a-4e41-b070-fb6d703dc45f" finished successfully.
    Operation "operations/acf.p2-783965148085-de4f0675-e9d1-4b66-8fd6-9ecf662d56cd" finished successfully.
    "INFO: dry-run mode, would run:" gcloud services disable --force oslogin.googleapis.com --project=k8s-infra-e2e-scale-5k-project
    "INFO: dry-run mode, would run:" gcloud services disable --force pubsub.googleapis.com --project=k8s-infra-e2e-scale-5k-project
    "INFO: dry-run mode, would run:" gcloud services disable --force storage-api.googleapis.com --project=k8s-infra-e2e-scale-5k-project
    WARN: ensure_only_services: after enable/disable cycle, still projects to enable/disable: k8s-infra-e2e-scale-5k-project
    intent:
      - compute.googleapis.com
      - containerregistry.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com
      - storage-component.googleapis.com
    enabled:
      - compute.googleapis.com
      - containerregistry.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com
      - oslogin.googleapis.com
      - pubsub.googleapis.com
      - storage-api.googleapis.com
      - storage-component.googleapis.com
    expected:
      - compute.googleapis.com
      - containerregistry.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com
      - storage-component.googleapis.com
    to_enable: []
    to_disable:
      - oslogin.googleapis.com
      - pubsub.googleapis.com
      - storage-api.googleapis.com
    @@ -4,17 +4,23 @@ intent:
       - logging.googleapis.com
       - monitoring.googleapis.com
       - storage-component.googleapis.com
    -enabled: []
    -expected:
    +enabled:
       - compute.googleapis.com
       - containerregistry.googleapis.com
       - logging.googleapis.com
       - monitoring.googleapis.com
    +  - oslogin.googleapis.com
    +  - pubsub.googleapis.com
    +  - storage-api.googleapis.com
       - storage-component.googleapis.com
    -to_enable:
    +expected:
       - compute.googleapis.com
       - containerregistry.googleapis.com
       - logging.googleapis.com
       - monitoring.googleapis.com
       - storage-component.googleapis.com
    -to_disable: []
    +to_enable: []
    +to_disable:
    +  - oslogin.googleapis.com
    +  - pubsub.googleapis.com
    +  - storage-api.googleapis.com
    Empower prow-build service account to edit e2e project: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -2,6 +2,8 @@
       role: roles/editor
     - member: serviceAccount:783965148085@cloudservices.gserviceaccount.com
       role: roles/editor
    +- member: serviceAccount:prow-build@k8s-infra-prow-build.iam.gserviceaccount.com
    +  role: roles/editor
     - member: serviceAccount:service-783965148085@compute-system.iam.gserviceaccount.com
       role: roles/compute.serviceAgent
     - member: serviceAccount:service-783965148085@containerregistry.iam.gserviceaccount.com
    Empower boskos-janitor service account to clean e2e project: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -2,6 +2,8 @@
       role: roles/editor
     - member: serviceAccount:783965148085@cloudservices.gserviceaccount.com
       role: roles/editor
    +- member: serviceAccount:boskos-janitor@k8s-infra-prow-build.iam.gserviceaccount.com
    +  role: roles/editor
     - member: serviceAccount:prow-build@k8s-infra-prow-build.iam.gserviceaccount.com
       role: roles/editor
     - member: serviceAccount:service-783965148085@compute-system.iam.gserviceaccount.com
    Empower k8s-infra-prow-oncall@kubernetes.io to admin e2e project: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -1,3 +1,5 @@
    +- member: group:k8s-infra-prow-oncall@kubernetes.io
    +  role: roles/owner
     - member: serviceAccount:783965148085-compute@developer.gserviceaccount.com
       role: roles/editor
     - member: serviceAccount:783965148085@cloudservices.gserviceaccount.com
    Empower k8s-infra-prow-viewers@kubernetes.io to view specific resources in e2e project: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -1,5 +1,7 @@
     - member: group:k8s-infra-prow-oncall@kubernetes.io
       role: roles/owner
    +- member: group:k8s-infra-prow-viewers@kubernetes.io
    +  role: organizations/758905017065/roles/prow.viewer
     - member: serviceAccount:783965148085-compute@developer.gserviceaccount.com
       role: roles/editor
     - member: serviceAccount:783965148085@cloudservices.gserviceaccount.com
    Empower k8s-infra-sig-scalability-oncall@kubernetes.io to admin e2e project: k8s-infra-e2e-scale-5k-project
    Updated IAM policy for project [k8s-infra-e2e-scale-5k-project].
    @@ -2,6 +2,8 @@
       role: roles/owner
     - member: group:k8s-infra-prow-viewers@kubernetes.io
       role: organizations/758905017065/roles/prow.viewer
    +- member: group:k8s-infra-sig-scalability-oncall@kubernetes.io
    +  role: roles/owner
     - member: serviceAccount:783965148085-compute@developer.gserviceaccount.com
       role: roles/editor
     - member: serviceAccount:783965148085@cloudservices.gserviceaccount.com
    Ensure prow-build prowjobs are able to ssh to instances in e2e project: k8s-infra-e2e-scale-5k-project
    Updated [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-scale-5k-project].
    @@ -0,0 +1,2 @@
    +prow:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmYxHh/wwcV0P1aChuFLpl28w6DFyc7G5Xrw1F8wH1Re9AdxyemM2bTZ/PhsP3u9VDnNbyOw3UN00VFdumkFLjLf1WQ7Q6rZDlPjlw7urBIvAMqUecY6ae1znqsZ0dMBxOuPXHznlnjLjM5b7O7q5WsQMCA9Szbmz6DsuSyCuX0It2osBTN+8P/Fa6BNh3W8AF60M7L8/aUzLfbXVS2LIQKAHHD8CWqvXhLPuTJ03iSwFvgtAK1/J2XJwUP+OzAFrxj6A9LW5ZZgk3R3kRKr0xT/L7hga41rB1qy8Uz+Xr/PTVMNGW+nmU4bPgFchCK0JBK7B12ZcdVVFUEdpaAiKZ prow
    +prow:prow:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmYxHh/wwcV0P1aChuFLpl28w6DFyc7G5Xrw1F8wH1Re9AdxyemM2bTZ [...]

2021-06-18 22:31 UTC, ameukam commented
Ref https://github.com/kubernetes/k8s.io/issues/2241