Release-1.23: Add 1.23 RT Leads to relevant groups
kubernetes/k8s.io pull request #2541
Opened 2021-08-14 00:09 UTC by reylejano

Add @JamesLaverack @jrsapi @mkorbi @MonzElmasry @reylejano to the following:
- leads@
- release-managers@
- release-team@
- release-comms@

Offboard 1.22 RT Leads.

/assign
/sig release
/priority critical-urgent
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco @hasheddan
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry

2021-08-14 00:44 UTC, dims commented
```
--- FAIL: TestNoDuplicateMembers (0.00s)
    groups_test.go:290: group 'release-comms@kubernetes.io' owner 'jeremy.r.rickard@gmail.com' cannot also be listed as a member
FAIL
```

2021-08-15 15:20 UTC, JamesLaverack commented
/lgtm

2021-08-16 07:56 UTC, saschagrunert approved these changes
/lgtm

2021-08-16 16:20 UTC, spiffxp requested changes
I must have missed this last time, why are we PR'ing in people who aren't SIG/WG/UG leads into a group whose description is "SIG/WG/UG leads" ?

Anyone can post to leads@, and anyone can view leads@, so it's not clear to me why this is necessary

2021-08-16 16:20 UTC, spiffxp commented on groups/groups.yaml
> +      - james.laverack@jetstack.io
I don't see this person listed as a SIG/WG/UG lead in kubernetes/community?

2021-08-16 16:20 UTC, spiffxp commented on groups/groups.yaml
> +      - joseph.r.sandoval@gmail.com
I don't see this person listed as a SIG/WG/UG lead in kubernetes/community?

2021-08-16 16:20 UTC, spiffxp commented on groups/groups.yaml
> +      - max@koerbaecher.io
I don't see this person listed as a SIG/WG/UG lead in kubernetes/community?

2021-08-16 16:20 UTC, spiffxp commented on groups/groups.yaml
> +      - monmonmsc@gmail.com
I don't see this person listed as a SIG/WG/UG lead in kubernetes/community?

2021-08-16 16:21 UTC, spiffxp commented
/cc @mrbobbytables @cblecker @nikhita @alisondy

2021-08-16 18:32 UTC, cblecker commented
+1, the intent of leads@ is for sig/wg leads, not for release team leads

2021-08-16 18:45 UTC, jeremyrickard commented
For reference, I think this has been done for the past few releases:

https://github.com/kubernetes/k8s.io/pull/1933
https://github.com/kubernetes/k8s.io/pull/1513
https://github.com/kubernetes/k8s.io/pull/1220

2021-08-16 18:58 UTC, justaugustus requested changes
@reylejano -- When you have a chance, please:
- drop the changes to leads@
- update our RT leads onboarding template to remove this requirement

> I must have missed this last time, why are we PR'ing in people who aren't SIG/WG/UG leads into a group whose description is "SIG/WG/UG leads" ?
> 
> Anyone can post to leads@, and anyone can view leads@, so it's not clear to me why this is necessary

> +1, the intent of leads@ is for sig/wg leads, not for release team leads

@spiffxp @cblecker -- The onboarding issue template (I believe) predates the leads@ list (in fact, makes mention of kubernetes-sig-leads) instead.

This was a documentation miss and we'll get that cleaned up.

Could also be related to the fact that `AllowWebPosting` was not configured for groups, so you needed to be a member to actually track convos (ref: https://github.com/kubernetes/k8s.io/pull/1332)

2021-08-16 18:59 UTC, justaugustus commented
/hold for fixes

2021-08-16 19:11 UTC, spiffxp commented
>For reference, I think this has been done for the past few releases and this is just following those as an example:

Yeah I'm not trying to shoot the messenger here, just taking the opportunity to ask what's going on and why.  Sounds like we don't need this anymore, always happy to see processes simplified

2021-08-16 19:53 UTC, reylejano commented
Reverted the changes to leads in `groups/groups.yaml`

2021-08-16 20:47 UTC, spiffxp approved these changes
/approve
/lgtm
Given earlier lgtm from sig release

2021-08-16 20:56 UTC, justaugustus commented
For SIG Release:
/lgtm
/approve

@spiffxp -- Feel free to drop the hold when y'all are ready to actuate.

2021-08-16 22:43 UTC, spiffxp commented
/hold cancel

2021-08-16 22:48 UTC, merged

2021-08-16 23:42 UTC, justaugustus commented
>     * update our RT leads onboarding template to remove this requirement

Thanks @reylejano for https://github.com/kubernetes/sig-release/pull/1666!