Add Terraform subrepo for monitoring
kubernetes/k8s.io pull request #2898
Opened 2021-10-08 10:19 UTC by ameukam

Related to:
 - Ref: https://github.com/kubernetes/k8s.io/issues/2588

Bootstrap a new suberepo that will host the Terraform resources
consuming the GCP monitoring API.
I also bumped the terraform provider for this subrepo and will the other
declarations of the provider in a followup PR.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2021-10-08 10:20 UTC, ameukam commented
I'll deploy it post-merge. 

cc @dims @spiffxp

2021-10-08 19:10 UTC, spiffxp requested changes
Why not do this in `terraform/kubernetes-public`? I feel like this is prototyping auto-deploy of terraform resources we don't think are dangerous to accidentally delete, I would like to see more discussion around that first.

2021-10-13 22:42 UTC, spiffxp approved these changes
/approve
/lgtm
/hold
Remove when ready to deploy

2021-10-14 04:46 UTC, ameukam commented
/hold cancel

2021-10-14 04:49 UTC, merged

2021-10-14 05:27 UTC, ameukam commented
Created the terraform stated :

```shell
terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/google-beta from the dependency lock file
- Using previously-installed hashicorp/google v3.87.0
- Using previously-installed hashicorp/google-beta v3.87.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

```shell
terraform apply -auto-approve

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```