add 1.27 release team shadows to needed groups
kubernetes/k8s.io pull request #4625
Opened 2023-01-12 21:56 UTC by salaxander

PR to finalize the needed access for the 1.27 release team

2023-01-14 00:42 UTC, harshanarayana requested changes

2023-01-14 00:42 UTC, harshanarayana commented on groups/sig-release/groups.yaml
> +      - lauralorenz@google.com # 1.27 CI Signal Lead
Seems like @AnaMMedina21 's name has been missing in this list. Can we please include her as well?

2023-01-17 20:22 UTC, palnabarun commented
/label tide/merge-method-squash

2023-01-17 20:23 UTC, palnabarun commented
/cc @kubernetes/sig-release-leads

2023-01-17 21:09 UTC, jeremyrickard approved these changes

2023-01-17 21:12 UTC, merged