Add bug triage shadows to release-team-shadows email group
kubernetes/k8s.io pull request #5311
Opened 2023-05-22 15:30 UTC by hailkomputer

Adding bug triage team shadows' emails for release v1.28 to the `release-team-shadows` group. I noticed the emails were missing, meaning we shadows may have missed some communication in the mean time.

cc @furkatgofurov7 @leonardpahlke @gracenng

2023-05-22 15:49 UTC, furkatgofurov7 requested changes

2023-05-22 15:49 UTC, furkatgofurov7 commented on groups/sig-release/groups.yaml
> +      - a.zelyk@reply.de # 1.28 Bug Triage Shadow
let's align this with https://github.com/kubernetes/k8s.io/pull/5272
```suggestion
      - zelikangelina@gmail.com # 1.28 Bug Triage Shadow
```

2023-05-22 16:00 UTC, furkatgofurov7 approved these changes
Thanks!

/approve
/lgtm

2023-05-23 17:33 UTC, gracenng commented
woops my bad!!
/approve

2023-05-23 17:39 UTC, gracenng commented
/approve
thanks for catching this

2023-05-23 20:04 UTC, helayoty commented
/lgtm
/approve

2023-05-23 20:41 UTC, jeremyrickard commented
/approve

2023-05-23 20:44 UTC, merged