.*: phase out ContribEx leads <3
kubernetes/k8s.io pull request #6117
Opened 2023-11-24 09:00 UTC by MadhavJivrajani

Ref: https://github.com/kubernetes/community/issues/7623

/hold 
/assign @kubernetes/sig-contributor-experience-leads

2023-11-24 09:51 UTC, Priyankasaggu11929 commented
/lgtm
/approve

/hold 
if any further changes are required.

2023-11-24 10:19 UTC, ameukam commented
Duplicate of https://github.com/kubernetes/k8s.io/pull/6115 ?

2023-11-27 21:28 UTC, upodroid requested changes

2023-11-27 21:28 UTC, upodroid commented on OWNERS
> +- cblecker
Please rebase and don't change this file. It was changed in #6115. Rest of the diff looks good

/approve

2024-01-03 23:24 UTC, cblecker commented
/lgtm

2024-01-06 00:26 UTC, cblecker commented
/hold cancel

2024-01-06 00:36 UTC, merged