feat: adds secrets-store-sync-controller project
kubernetes/k8s.io pull request #7048
Opened 2024-07-22 22:58 UTC by nilekhc

- `secrets-store-sync-controller` is the new spin-off project from `secrets-store-csi-driver` sponsored by SigAuth and added to kubernetes-sigs
- onboarding the project, so we can start publishing the images to `registry.k8s.io`

/cc @aramase @enj 
/assign @dims

2024-07-23 01:27 UTC, dims commented
/assign @upodroid

2024-07-25 19:34 UTC, nilekhc commented
@upodroid Could you PTAL when you get a chance? Thanks.

2024-07-25 20:40 UTC, upodroid requested changes

2024-07-25 20:40 UTC, upodroid commented on registry.k8s.io/manifests/k8s-staging-secrets-store-sync/promoter-manifest.yaml
> +- name: gcr.io/k8s-staging-secrets-store-sync
```suggestion
- name: us-central1-docker.pkg.dev/k8s-staging-images/secrets-store-sync
```

2024-07-25 20:40 UTC, upodroid commented on registry.k8s.io/manifests/k8s-staging-secrets-store-sync/promoter-manifest.yaml
> +- name: gcr.io/k8s-staging-secrets-store-sync
Please push your staging images to this registry please.

2024-07-29 19:03 UTC, nilekhc commented
@upodroid I have updated the PR. PTAL. Thanks.

2024-07-29 22:21 UTC, upodroid commented on registry.k8s.io/images/k8s-staging-secrets-store-sync/generate.sh
> +    secrets-store-sync-controller
```suggestion
    controller
```

2024-07-29 22:21 UTC, upodroid commented on registry.k8s.io/images/k8s-staging-secrets-store-sync/generate.sh
> +readonly repo="gcr.io/k8s-staging-secrets-store-sync"
us-central1-docker.pkg.dev/k8s-staging-images/secrets-store-sync
```suggestion
readonly repo="gcr.io/k8s-staging-secrets-store-sync"
```

2024-07-29 22:47 UTC, upodroid approved these changes
Thanks

2024-07-30 00:22 UTC, merged